### PR TITLE
Flesh out the archetypes with addtional documentation and tips

### PR DESCRIPTION
**Pull request by tristantarrant**
- Include detailed documentation within the methods of the custom loaders/stores
- Provide a concrete example of parsing elements/attributes
- Add the JBoss repositories

### CODE REVIEW

**Comment by galderz** [comment]
Looks good, are you waiting for someone else's feedback?

**Comment by tristantarrant** [comment]
if you're happy with it :)

**Comment by tristantarrant** [comment]
This can be pulled

**Comment by galderz** [comment]
Integrated

**Pull request closed without merging**
